openapi: 3.0.0
info:
  title: Zefa Finance API
  version: 0.2.0
  description: >
    Zefa Finance API (MVP).
    Uses JWT Bearer authentication (OAuth2 Password flow at POST /token).
    Main flow: register -> login -> access protected routes with Authorization: Bearer <token>.

servers:
  - url: http://localhost:8000
    description: Local development server

tags:
  - name: meta
    description: Health and meta endpoints
  - name: auth
    description: Authentication
  - name: user
    description: User profile (authenticated user configuration)
  - name: transactions
    description: Transactions CRUD (create/list/update/delete)
  - name: dashboard
    description: Financial summaries
  - name: chat
    description: AI chat agent endpoints

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    # --- Auth ---
    UserCreate:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8

    Token:
      type: object
      required: [access_token, token_type]
      properties:
        access_token:
          type: string
        token_type:
          type: string
          example: bearer

    TokenRefreshRequest:
      type: object
      description: Optional body for refresh token exchange; normally the token is taken from an HTTP-only cookie.
      properties:
        refresh_token:
          type: string
          description: Opaque refresh token value (used mainly for non-browser clients).

    # --- Transactions ---
    TransactionType:
      type: string
      enum: [INCOME, EXPENSE]

    TransactionCreate:
      type: object
      required: [amount, type, category]
      properties:
        amount:
          type: number
          format: float
          minimum: 0.01
        type:
          $ref: "#/components/schemas/TransactionType"
        category:
          type: string
        description:
          type: string
          nullable: true
        occurred_at:
          type: string
          format: date-time
          nullable: true

    TransactionUpdate:
      type: object
      description: Partial update schema (all fields optional for PATCH)
      properties:
        amount:
          type: number
          format: float
          minimum: 0.01
        type:
          $ref: "#/components/schemas/TransactionType"
        category:
          type: string
        description:
          type: string
          nullable: true
        occurred_at:
          type: string
          format: date-time
          nullable: true

    TransactionResponse:
      allOf:
        - $ref: "#/components/schemas/TransactionCreate"
        - type: object
          required: [id, created_at, occurred_at]
          properties:
            id:
              type: string
              format: uuid
            occurred_at:
              type: string
              format: date-time
            created_at:
              type: string
              format: date-time

    # --- Dashboard ---
    CategoryMetric:
      type: object
      required: [name, value]
      properties:
        name:
          type: string
        value:
          type: number
          format: float

    DashboardSummary:
      type: object
      required: [total_balance, total_income, total_expense, by_category]
      properties:
        total_balance:
          type: number
          format: float
        total_income:
          type: number
          format: float
        total_expense:
          type: number
          format: float
        by_category:
          type: array
          items:
            $ref: "#/components/schemas/CategoryMetric"

    # --- User Profile ---
    UserProfileResponse:
      type: object
      required: [email, monthly_budget]
      properties:
        email:
          type: string
          format: email
        full_name:
          type: string
          nullable: true
        monthly_budget:
          type: number
          format: float
          minimum: 0.01
          description: Monthly budget for dashboard calculations (uses DEFAULT_MONTHLY_BUDGET when null at creation).

    UserProfileUpdate:
      type: object
      description: Partial update for authenticated user profile (all fields optional).
      properties:
        full_name:
          type: string
          nullable: true
        monthly_budget:
          type: number
          format: float
          minimum: 0.01
          nullable: true

    # --- Chat ---
    ChatMessageCreate:
      type: object
      required: [text]
      properties:
        text:
          type: string
          description: User message text.
        conversation_id:
          type: string
          format: uuid
          nullable: true
          description: Conversation ID. If omitted, a new conversation is created.
        content_type:
          type: string
          enum: [text]
          default: text
          description: Content type (MVP supports text only).

    ChatMessage:
      type: object
      required: [id, conversation_id, role, content, content_type, created_at]
      properties:
        id:
          type: string
          format: uuid
        conversation_id:
          type: string
          format: uuid
        role:
          type: string
          enum: [user, assistant]
        content:
          type: string
          description: Assistant responses may contain Markdown.
        content_type:
          type: string
          example: text
        created_at:
          type: string
          format: date-time

    ChatUiEvent:
      type: object
      required: [type, variant, accent, title]
      properties:
        type:
          type: string
          enum: [success_card, warning_card, info_card]
        variant:
          type: string
          enum: [neon]
          default: neon
        accent:
          type: string
          enum: [electric_lime, deep_indigo]
          default: electric_lime
        title:
          type: string
        subtitle:
          type: string
          nullable: true
        data:
          type: object
          nullable: true
          description: Flexible payload (e.g., { transaction: {...} }).
          additionalProperties: true

    ChatAssistantMeta:
      type: object
      required: [ui_events, did_create_transaction, insight_tags]
      properties:
        ui_events:
          type: array
          items:
            $ref: "#/components/schemas/ChatUiEvent"
        did_create_transaction:
          type: boolean
          default: false
        created_transaction_id:
          type: string
          format: uuid
          nullable: true
        did_update_transaction:
          type: boolean
          default: false
        updated_transaction_id:
          type: string
          format: uuid
          nullable: true
        did_delete_transaction:
          type: boolean
          default: false
        deleted_transaction_id:
          type: string
          format: uuid
          nullable: true
        insight_tags:
          type: array
          items:
            type: string

    ChatMessageResponse:
      type: object
      required: [message, meta]
      properties:
        message:
          $ref: "#/components/schemas/ChatMessage"
        meta:
          $ref: "#/components/schemas/ChatAssistantMeta"

    ApiKeyRequest:
      type: object
      required: [api_key]
      properties:
        api_key:
          type: string
          description: Provider API key (OpenAI/Anthropic/Gemini).

    ApiKeyResponse:
      type: object
      required: [message]
      properties:
        message:
          type: string

security:
  - bearerAuth: []

paths:
  # --- Meta ---
  /:
    get:
      tags: [meta]
      summary: Root endpoint
      description: Basic API info.
      security: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  version:
                    type: string

  /health:
    get:
      tags: [meta]
      summary: Health check
      description: Returns API health status.
      security: []
      responses:
        "200":
          description: Healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy

  # --- Public Auth ---
  /auth/register:
    post:
      tags: [auth]
      summary: Register a new user
      description: Creates a new user and returns an access token for immediate use.
      operationId: register_user
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreate"
      responses:
        "201":
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "400":
          description: Email already registered.

  /token:
    post:
      tags: [auth]
      summary: Login (get token)
      description: OAuth2-compatible form login. Sends username (email) and password, returns JWT.
      operationId: login
      security: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                  description: User email.
                password:
                  type: string
                  format: password
      responses:
        "200":
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "401":
          description: Invalid credentials.

  /auth/refresh:
    post:
      tags: [auth]
      summary: Refresh access token
      description: >
        Exchanges a valid refresh token for a new access token.
        The refresh token is primarily sent as an HTTP-only cookie (refresh_token), but an optional JSON body is supported.
      operationId: refresh_access_token
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TokenRefreshRequest"
      responses:
        "200":
          description: New access token issued.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Token"
        "401":
          description: Missing, invalid, or expired refresh token.

  /auth/logout:
    post:
      tags: [auth]
      summary: Logout and revoke refresh token
      description: >
        Revokes the current refresh token and clears the corresponding cookie so it can no longer be used.
      operationId: logout
      responses:
        "204":
          description: Logged out; refresh token revoked and cookie cleared.

  # --- User Profile (protected) ---
  /user/profile:
    get:
      tags: [user]
      summary: Get user profile
      description: Returns the authenticated user's profile (email, full_name, monthly_budget).
      operationId: get_user_profile
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfileResponse"
        "401":
          description: Unauthorized (missing or invalid token)
    patch:
      tags: [user]
      summary: Update user profile
      description: Updates the authenticated user's profile (partial update).
      operationId: update_user_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfileUpdate"
      responses:
        "200":
          description: Updated profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfileResponse"
        "400":
          description: Validation error (e.g., monthly_budget <= 0)
        "401":
          description: Unauthorized

  # --- Protected Auth (helper) ---
  /auth/me:
    get:
      tags: [auth]
      summary: Get current user info (helper)
      description: Returns basic info about the currently authenticated user. Useful for testing.
      operationId: auth_me
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string

  # --- Transactions (protected) ---
  /transactions:
    get:
      tags: [transactions]
      summary: List transactions
      description: Returns transaction history for the authenticated user.
      operationId: list_transactions
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 200
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TransactionResponse"

    post:
      tags: [transactions]
      summary: Create transaction
      description: Creates a new transaction for the authenticated user.
      operationId: create_transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionCreate"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "400":
          description: Validation error (e.g., amount must be positive).

  /transactions/{transaction_id}:
    patch:
      tags: [transactions]
      summary: Update transaction
      description: Updates a transaction if it belongs to the authenticated user. Supports partial updates (PATCH semantics).
      operationId: update_transaction
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionUpdate"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionResponse"
        "404":
          description: Not found (does not exist or does not belong to user).
        "422":
          description: Validation error (e.g., amount must be positive).

    delete:
      tags: [transactions]
      summary: Delete transaction
      description: Deletes a transaction if it belongs to the authenticated user.
      operationId: delete_transaction
      parameters:
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Deleted
        "404":
          description: Not found (does not exist or does not belong to user).

  # --- Dashboard (protected) ---
  /dashboard/summary:
    get:
      tags: [dashboard]
      summary: Get financial summary
      description: Returns totals (balance/income/expense) and expense breakdown by category.
      operationId: get_dashboard_summary
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DashboardSummary"

  # --- Chat (protected) ---
  /chat/messages:
    post:
      tags: [chat]
      summary: Send a chat message
      description: >
        Sends a user message to Zefa and returns the assistant response with UI metadata.
        If conversation_id is provided, the conversation continues; otherwise a new conversation is created.
        The response includes message content and metadata (UI events, transaction creation flags, insights).
      operationId: create_chat_message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChatMessageCreate"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ChatMessageResponse"
        "400":
          description: Message text is required.
        "502":
          description: AI gateway error while processing the message.

  /chat/api-key:
    post:
      tags: [chat]
      summary: Set an ephemeral provider API key
      description: >
        Stores a provider API key in memory only (per user) and expires it after 60 minutes.
        Useful for development when environment variables are not set.
      operationId: set_api_key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApiKeyRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiKeyResponse"
